# Learning Unit 3 — Data Exploration & Reproducibility

## Part 1: Dataset exploration

In this learning unit you will investigate how datasets are typically presented when acquired online. In particular, you will look at what information is provided with the datasets, what is usually included, and what is often missing.

Go the UCI Machine Learning repository and look at the [dataset submission](https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data). Then click on `Download`and unpack the zip-file. Take a moment to examine the provided files.

**✏️ Task 1** 
*Try to answer the following questions by examining the information provided on the UCI ML repository site and the supplemental files!*
- *Who created the dataset?*
- *When was the dataset created?*
- *Who paid for the dataset creation?*
- *What bank is the data from?*
- *What processing was done on the data?*
- *What does each attribute mean?*

- *Who created the dataset?* The dataset was created by Professor Dr. Hans Hofmann from the Institut für Statistik und Ökonometrie, Universität Hamburg.

- *When was the dataset created?* The files are dated November 17, 1994, so the dataset was most likely created around 1994.

- *Who paid for the dataset creation?* No information found.

- *What bank is the data from?* No information found.

- *What processing was done on the data?* 2 versions of the dataset exist. The original (german.data) has categorical/symbolic attributes as provided by Prof. Hofmann. A 2nd version (german.data-numeric) was produced by Strathclyde University where several indicator variables were added to convert categorical variables into numerical ones so that algorithms that can't handle categorical data could use it.

- *What does each attribute mean?* 
Attribute 1:  (qualitative)
	       Status of existing checking account

Attribute 2:  (numerical)
	      Duration in month

Attribute 3:  (qualitative)
	      Credit history

Attribute 4:  (qualitative)
	      Purpose of the credit

Attribute 5:  (numerical)
	      Credit amount

Attibute 6:  (qualitative)
	      Savings account/bonds

Attribute 7:  (qualitative)
	      Present employment duration

Attribute 8:  (numerical)
	      Installment rate in percentage of disposable income

Attribute 9:  (qualitative)
	      Personal status and sex

Attribute 10: (qualitative)
	      Other debtors / guarantors

Attribute 11: (numerical)
	      Present residence duration

Attribute 12: (qualitative)
	      Property owned

Attribute 13: (numerical)
	      Age in years

Attribute 14: (qualitative)
	      Other installment plans

Attribute 15: (qualitative)
	      Housing situation

Attribute 16: (numerical)
              Number of existing credits at this bank

Attribute 17: (qualitative)
	      Job type

Attribute 18: (numerical)
	      Number of people being liable to provide maintenance for

Attribute 19: (qualitative)
	      Telephone registered under customer's name

Attribute 20: (qualitative)
	      Whether the person is a foreign worker

### Analyzing the German Credit Data
Were you able to answer all of the questions? If not, don't worry, sometimes this information is not provided or is difficult to find. For now, let's continue to examine the contents of the dataset.

The content is contained in the `german.data`-file. Open the file with your favorite text editor and take a moment to examine the contents. It will be difficult for you to interpret the meaning of the data because it is encoded, i.e., integers instead of a human-understandable string. So to interpret the data, you need to use the coding table in the `german.doc` file and look up the meaning of the numbers.

Fortunately, you don't have to do that. Along with this notebook, we have also provided you with a file called `german_credit_data_processed.csv'. This file has been created by replacing the integers with the values from the coding table. Please use this file for the following task as it will make it easier for you.

**✏️ Task 1.2** 
*Analyze the German Credit data using the python data analysis skills you learned in the previous learning unit and in other courses. Write your analysis results in python & markdown cells below. Indicate if you notice anything unusual!*

*Questions you might want to consider for your analysis:*
- *What can you say about the features?*
- *What are the proportions of applicants belonging to a certain feature?*
- *How are the distributions of the features?*
- *Who is considered to have a good or bad credit risk?*

# Your data analysis code

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv('german_credit_data_processed.csv')
print(df.shape)
df.head()

# The dataset has 1000 rows and 21 columns. Out of 21 columns 20 of them are features and target is 'goodness'.

(1000, 21)

,checking account,duration in month,credit history,credit purpose,credit amount,savings account,employment since..,installment rate,status : sex,other debtors / guarantors,...,property,relationship : age,other installment plans,housing,existing credits,job,people to provide maintenance for,telephone,foreign worker,goodness
0,negative,6,critical account,radio OR tv,1169,unknown OR no savings account,7y <= ...,4,male : single,none,...,real estate,67,none,own,2,skilled employed OR official,1,yes,yes,1
1,0 <= ... <= 200,48,existing AND duly paid,radio OR tv,5951,... < 100,1 <= ... < 4y,2,female : married OR separated OR divorced,none,...,real estate,22,none,own,1,skilled employed OR official,1,no,yes,2
2,none,12,critical account,education,2096,... < 100,4 <= ... < 7y,2,male : single,none,...,real estate,49,none,own,1,unskilled - resident,2,no,yes,1
3,negative,42,existing AND duly paid,furniture,7882,... < 100,4 <= ... < 7y,2,male : single,guarantor,...,society savings agreement OR life insurance,45,none,for free,1,skilled employed OR official,2,no,yes,1
4,negative,24,delayed,car (new),4870,... < 100,1 <= ... < 4y,3,male : single,none,...,none OR unknown,53,none,for free,2,skilled employed OR official,2,no,yes,2

In [33]:
df.dtypes

# There are 7 numerical and 13 categorical features, which matches the provided documentation.

checking account                       str
duration in month                    int64
credit history                         str
credit purpose                         str
credit amount                        int64
savings account                        str
employment since..                     str
installment rate                     int64
status : sex                           str
other debtors / guarantors             str
residence since                      int64
property                               str
relationship : age                   int64
other installment plans                str
housing                                str
existing credits                     int64
job                                    str
people to provide maintenance for    int64
telephone                              str
foreign worker                         str
goodness                             int64
dtype: object

In [34]:
df.isnull().sum()

# checking for missing values - No missing values

checking account                     0
duration in month                    0
credit history                       0
credit purpose                       0
credit amount                        0
savings account                      0
employment since..                   0
installment rate                     0
status : sex                         0
other debtors / guarantors           0
residence since                      0
property                             0
relationship : age                   0
other installment plans              0
housing                              0
existing credits                     0
job                                  0
people to provide maintenance for    0
telephone                            0
foreign worker                       0
goodness                             0
dtype: int64

In [35]:
num_cols = ['duration in month', 
            'credit amount', 
            'installment rate',
            'residence since', 
            'relationship : age', 
            'existing credits', 
            'people to provide maintenance for']

df[num_cols].describe()

# Average loan duration is around 21 months, but it can go up to 72 months
# Ages range from 19 to 75, with an average of around 35 years.

,duration in month,credit amount,installment rate,residence since,relationship : age,existing credits,people to provide maintenance for
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [36]:
print(df['goodness'].value_counts())

# 70% of applicants are classified as Good (1) and 30% as Bad (2). This is an imbalanced dataset.

goodness
1    700
2    300
Name: count, dtype: int64

In [37]:
df['checking account'].value_counts()

# Almost 40% of applicants have no checking account at all, yet they still applied for credit.

checking account
none                394
negative            274
 0 <= ... <= 200    269
200 < ...            63
Name: count, dtype: int64

In [38]:
df['credit history'].value_counts()

# More than half have existing credits that are being paid on time.

credit history
existing AND duly paid    530
critical account          293
delayed                    88
duly paid                  49
none OR duly paid          40
Name: count, dtype: int64

In [39]:
df['credit purpose'].value_counts()

# Top 3 purposes are radio/TV, new car, and furniture

credit purpose
radio OR tv            280
car (new)              234
furniture              181
car (used)             103
business                97
education               50
repairs                 22
domestic appliances     12
other                   12
retraining               9
Name: count, dtype: int64

In [40]:
df['savings account'].value_counts()

# Over 60% of applicants have less than 100 DM (Deutsche Mark) in savings and  18% have no savings account at all.

savings account
 ... < 100                       603
unknown OR no savings account    183
100 <= ... < 500                 103
500 <= ... < 1000                 63
1000 <= ...                       48
Name: count, dtype: int64

In [41]:
df['employment since..'].value_counts()

# Most applicants are employed. Only 6.2% are unemployed. The largest group is the people with 1–4 years of employment.

employment since..
1 <= ... < 4y    339
7y <= ...        253
4 <= ... < 7y    174
 ... < 1y        172
unemployed        62
Name: count, dtype: int64

In [42]:
df['status : sex'].value_counts()

# There is no 'female : single' category at all in this dataset.

status : sex
male : single                                548
female : married OR separated OR divorced    310
male : married                                92
male : separated OR divorced                  50
Name: count, dtype: int64

In [43]:
df['housing'].value_counts()

# 71.3% own their home which may contradict with low savings balance.

housing
own         713
rent        179
for free    108
Name: count, dtype: int64

In [44]:
df['foreign worker'].value_counts()

# 96.3% of applicants are foreign workers which is the most unusual finding in the dataset.

foreign worker
yes    963
no      37
Name: count, dtype: int64

### Analyzing other popular datasets
We will continue with a dataset called *“CDC Diabetes Health Indicators”*. We will keep using this dataset during the semester, so it makes sense to take your time and get familiar with it.

You can find more information about the dataset it in the UCI ML Library [here](https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators). In the provided resource you will find a file called `diabetes_012_health_indicators_BRFSS2015.csv`, which is one of three csv files in the dataset.

**✏️ Task 1.3** *Take a close look at the documentation and try to answer the following questions for it! Write down your findings in the Markdown cell below.*

*Questions to explore:*
- *Who created the dataset?*
- *For what purpose was the dataset created?*
- *Who funded the dataset creation?*
- *How was the dataset collected?*
- *How is the data sampled? Does the sampling make sense?*
- *Does the dataset make any assumptions?*
- *Were there data points that have been specifically left out?*
- *Are there any known errors or inconsistencies in the dataset?*
- *Are there missing values?*
- *Is the meaning behind every attribute in the dataset clear?*
- *Does the dataset contain metadata, e.g., a README file?*

- *Who created the dataset?* The dataset was created by the CDC (Centers for Disease Control and Prevention) through their BRFSS (Behavioral Risk Factor Surveillance System) survey.

- *For what purpose was the dataset created?* To better understand the relationship between  lifestyle and diabetes in the US.

- *Who funded the dataset creation?* The CDC.

- *How was the dataset collected?* The dataset is built from a combined landline and cell phone survey. It includes data from all 50 states.

- *How is the data sampled? Does the sampling make sense?* The 2014 BRFSS data reflects changes initially made in 2011 in weighting methodology (Raking) and the addition of cell phone only respondents. 'Raking' is a statistical technique to make the sample more representative of the actual population.

- *Does the dataset make any assumptions?* It assumes self-reported answers are accurate.

- *Were there data points that have been specifically left out?*  Some things are likely excluded - like race, geographic identifiers etc. even though the original BRFSS collects it.

- *Are there any known errors or inconsistencies in the dataset?* The BRFSS 2014 data is not directly comparable to years of BRFSS data before 2011 because of the changes in weighting methodology and the addition of the cell phone sampling frame.

- *Are there missing values?* No.

- *Is the meaning behind every attribute in the dataset clear?* Mostly Yes.

- *Does the dataset contain metadata, e.g., a README file?* The CDC provides a full BRFSS Overview PDF covering background, data collection, processing, and statistical/analytical issues.

## Part 2: Reproducibility

In the lecture you learnt about *reusability* as one of the principles of reproducibile data science workflows. One central element for reusability is *executability*. A central goal here is to deal with the *"It works on my machine"* problem, as code may (and often does) behave differently on different machines and over time, mostly due to missing packages, version mismatches and OS differences.

You learnt that there are specific tools in python which help with virtualization and dependency management. Your goal now is to take your streamlit application code from last week's assigment and get it running in a virtual enviroment.

**Steps**:

1. Choose one of the following tools: **Docker**, **uv**, **Conda**, **poetry**. If you are struggling, choose the one you are most familiar with.
2. Setup the virtual environment with all needed dependencies.
3. Start your streamlit application via a single command **such that it is succesfully running in a browser window**.
4. Document the steps in a **Readme.md** file. It should be possible for someone completely unfamiliar with your code to setup the project just with the instructions in this file and the files provided.
4. Upload **all** of the deliverables as attachments. **Please make sure to not forget any file.**

**Deliverables**:

1. Your **Readme.md** file with setup instructions
2. Your environment file (depending on the chosen tool this will be a Dockerfile, pyproject.toml or environment.yaml)
3. Your **streamlit.py** file

**Evaluation criteria**: Your streamlit application must work on our machine.

# 📝 Feedback
We are interested in your feedback in order to improve this course. We will read all of your feedback and evaluate it. What you share may have a direct impact on the rest of the course or future iterations of it.

Write down your feedback on the lecture, the exercises, or the assignments in the Markdown cell below. Furthermore, please note the approximate time it took you to complete the assignment. You may also write about your insights, what you found interesting, or questions that you have.